### ISSUE TITLE
Does the sender need to identify the cryptographic payload as containing protected headers?

### ISSUE THREAD

**Issue by dkg** [autocrypt/protected-headers#21]
We still have this FIXME:

> - FIXME: Enigmail adds `protected-headers="v1"` parameter to the `Content-Type:` of the Cryptographic Payload.  Is this necessary?

My question is: do we need this?  If its presence would be actionable in some way, then yes, i think we need it.

If it is not actionable, then i don't see what we gain from it.

Until today, i didn't understand any actionable behavior from it.  But reading @BjarniRunar 's "Reverse-Copying" explanation, i realized that maybe it could be used as a clear signal to a receiving MUA that it *should* drop missing Exposed Headers.

**Comment by dkg** [comment]
Let me write this out in a bit more detail.

For this example, I'm considering this in the context of trying to defend against the [Participant Modification attack](https://tools.ietf.org/html/draft-autocrypt-lamps-protected-headers-01#section-11.3) on encrypted mail.

Alice receives an encrypted message, and the protected headers include `To`, `Date`, `From`, `Subject`, and `Message-Id`.

All of those headers match the exposed headers (whether the `Subject` is obscured is not relevant in this example).  The `From` header is from Bob, and the `To` header contains Alice and Carol.

But, the exposed headers also contain a `Cc`, with Dave in it.

Alice wants to "reply all" to the mail.  Should her MUA include Dave in the reply?

**Comment by pbrunschwig** [comment]
The `protected-headers` parameter was originally added, such that it was clear how to treat the `Legacy Display` text/rfc822-headers mime part. I don't think that it's strictly required, but may help to indicate how to treat the headers. 

In other words, the presence of the header parameter tells me that I have to enable processing of protected headers. Otherwise, I'd have to scan the other headers in the mime part to find out if any of them is present. Only if none of them is present, I would not do the protected headers processing.

**Comment by dkg** [comment]
Given this conversation, i think we do need to explicitly require they `protected-headers=v1` parameter on the content-type of the cryptographic payload.  I'll be making that change.
